AWSTemplateFormatVersion: 2010-09-09
Parameters:
  vpc1StackName: #ParameterKey
    Description: 'Name of your VPC1 CFN Stack'
    Type: String
    Default: 'vpc1'
Resources: 
  vpc1customSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'barnyar-master vpc1 Custom Security Group'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: '0.0.0.0/0'
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: '0.0.0.0/0'
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: '0.0.0.0/0'
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: '0.0.0.0/0'
      VpcId:
        Fn::ImportValue:
          !Sub ${vpc1StackName}-VPCID 
      Tags:
        - Key: 'Name'
          Value: 'barnyar Master vpc1 Security Group'
Outputs:
  vpc1customSecurityGroupID: #logicalID
    Description: 'barnyar Master vpc1 SecurityGroup ID'
    Value:
      !Ref vpc1customSecurityGroup # the vaule of export is here
    Export:
      Name:
        !Sub ${AWS::StackName}-vpc1SecurityGroupID # the name of infra-stack export